name: Deploy MkDocs

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site-qualite
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Installer des versions compatibles
        run: |
          pip install mkdocs-material==9.4.14
          pip install pymdown-extensions==9.11

      - name: Configurer Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Vérifier la configuration (optionnel)
        run: mkdocs build --strict  # pour voir si l'erreur est résolue avant de déployer

      - name: Déployer
        run: mkdocs gh-deploy --force